# Generated by Django 3.1.2 on 2020-10-12 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient_id', models.CharField(max_length=50)),
                ('document_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StructureModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_separator', models.CharField(max_length=20)),
                ('header_separator', models.CharField(max_length=20)),
                ('header_key_separator', models.CharField(max_length=20)),
            ],
        ),
    ]
